// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleCeilingLight() {
  return window['go']['main']['App']['HandleCeilingLight']();
}

export function HandleTv() {
  return window['go']['main']['App']['HandleTv']();
}

export function SleepNow() {
  return window['go']['main']['App']['SleepNow']();
}
